systore/sms/urls.py
from django.urls import path
from . import views

app_name = 'sms'

urlpatterns = [
    path('', views.index, name='index'),

    path('stock/', views.stock, name='stock'),
    path('stock/add', views.stock_add, name='stockadd'),

    path('bill/', views.bill, name='bill'),
    # path('analysis/', views.analysis, name='analysis'),
]

systore/systore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sms/', include('sms.urls')),
]

systore/sms/models.py
from django.db import models
from django.core.validators import MinValueValidator

class Stock(models.Model):
    goods_name = models.CharField(verbose_name='商品名', max_length=64)
    barcode = models.CharField(verbose_name='条码', max_length=13)
    pic = models.URLField(verbose_name='参考图', blank=True)
    num = models.IntegerField(verbose_name='数量', validators=[MinValueValidator(0, message='数量必须大于0'),])
    input_price = models.DecimalField(verbose_name='进货价', max_digits=7, decimal_places=2, validators=[MinValueValidator(0),])
    sale_price = models.DecimalField(verbose_name='零售价', max_digits=7, decimal_places=2)

    WAREHOUSE_A1 = 'A1'
    WAREHOUSE_A2 = 'A2'
    WAREHOUSE_A3 = 'A3'
    WAREHOUSE_CHOICES = [
        (WAREHOUSE_A1, 'A1'),
        (WAREHOUSE_A2, 'A2'),
        (WAREHOUSE_A3, 'A3'),
    ]
    warehouse = models.CharField(verbose_name='仓库', choices=WAREHOUSE_CHOICES, max_length=16, default=WAREHOUSE_A1)
    trade_mark = models.CharField(verbose_name='品牌', blank=True, max_length=64)

    GOODS_CLASS_PEN = '笔'
    GOODS_CLASS_JUICE = '饮料'
    GOODS_CLASS_CARD = '明星片'
    GOODS_CLASS_CHOICES = [
        (GOODS_CLASS_PEN, '笔'),
        (GOODS_CLASS_JUICE, '饮料'),
        (GOODS_CLASS_CARD, '明信片'),
    ]
    goods_class = models.CharField(verbose_name='品类', choices=GOODS_CLASS_CHOICES, max_length=16, default=GOODS_CLASS_PEN)
    spec = models.CharField(verbose_name='规格', blank=True, max_length=128)
    time_created = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    is_filed = models.BooleanField(verbose_name='是否归档', default=False)
    is_on_sale = models.BooleanField(verbose_name='是否上架', default=True)
    


systore/sms/forms.py
from django import forms
from .models import Stock


class StockForm(forms.ModelForm):
    class Meta:
        model = Stock
        fields = ['goods_name', 'barcode', 'pic', 'num', 'input_price', 'sale_price',
                  'warehouse', 'trade_mark', 'goods_class', 'spec',]

systore/sms/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.core.exceptions import ValidationError
import gettext as _

from .models import Stock
from .forms import StockForm


def index(request):
    return render(request, 'sms/index.html')


def stock(request):
    stocks = Stock.objects.order_by('time_created')
    context = {'stocks': stocks}
    return render(request, 'sms/stock.html', context)


def stock_add(request):
    if request.method != 'POST':
        form = StockForm()
    else:
        print('POST DATA', request.POST)
        form = StockForm(request.POST)
        if form.is_valid():
            print(1234556)
            # form.save()
            return HttpResponseRedirect(reverse('sms:stock'))
        else:
            raise ValidationError("sdfsffsfd")
    context = {'form': form}
    return render(request, 'sms/stock_add.html', context)


def bill(request):
    return render(request, 'sms/bill.html')

systore/sms/templates/sms/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <title>店铺管理系统</title>
    <link rel="stylesheet" type="text/css" href="{% static 'sms/main.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'sms/stock_add.css' %}" />
</head>

<body>
    <header>
        <h1>SMS</h1>
    </header>
    <nav>
        <ul>
            <li><a href="{% url 'sms:index' %}">首页</a></li>
            <li><a href="{% url 'sms:bill' %}">收银</a></li>
            <li><a href="{% url 'sms:stock' %}">库存</a></li>
            <li><a href="#">统计</a></li>
        </ul>
    </nav>
    <div id="tableContainer">
        <div id="tableRow">
            <section>
                {% block content %}
                {% endblock %}
            </section>
            <aside>
                {% block aside %}
                {% endblock %}
            </aside>
        </div>
    </div>

    <footer>
        <p>That all glory is fleeting.</p>
    </footer>

    <script src="https://unpkg.com/react@18/umd/react.development.js" crossorigin></script>
    <script src="https://unpkg.com/react-dom@18/umd/react-dom.development.js" crossorigin></script>
    <script src="{% static 'sms/stock_add.js' %}"></script>
</body>



</html>

systore/sms/templates/sms/base_stock.html
{% extends 'sms/base.html' %}

{% block aside %}
<ul>
    <li><a href="{% url 'sms:stock' %}">查询</a></li>
    <li><a href="{% url 'sms:stockadd' %}">新增</a></li>
</ul>
{% endblock %}

systore/sms/templates/sms/index.html
{% extends "sms/base.html" %}

{% block content %}

<p>hello world!!!</p>

{% endblock %}

{% block aside %}

<ul>
    <li>自定义1</li>
    <li>自定义2</li>
    <li>自定义3</li>
    <li>自定义4</li>
</ul>

{% endblock %}

systore/sms/templates/sms/stock.html
{% extends 'sms/base_stock.html' %}

{% block content %}
<table>
    <thead>
        <tr>
            <th>序号</th>
            <th>商品名</th>
            <th>条形码</th>
            <th>数量</th>
            <th>进货价</th>
            <th>零售价</th>
            <th>货架号</th>
            <th>品牌</th>
            <th>二级品类</th>
            <th>规格</th>
            <th>最近上架时间</th>
            <th>是否上架</th>
            <th>是否归档</th>
            <th>操作</th>
        </tr>
    </thead>
    <tbody>
        {% for stock in stocks %}
        <tr>
            <td>{{ stock.id }}</td>
            <td>{{ stock.goods_name }}</td>
            <td>{{ stock.barcode }}</td>
            <td>{{ stock.num }}</td>
            <td>{{ stock.input_price }}</td>
            <td>{{ stock.sale_price }}</td>
            <td>{{ stock.warehouse }}</td>
            <td>{{ stock.trade_mark }}</td>
            <td>{{ stock.goods_class }}</td>
            <td>{{ stock.spec }}</td>
            <td>{{ stock.time_created|date:'M d, Y H:i' }}</td>
            <td>√</td>
            <td></td>
            <td><a href="stock_detail.html">详情</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

systore/sms/templates/sms/stock_add.html
{% extends 'sms/base_stock.html' %}

{% block content %}

<form action="{% url 'sms:stockadd' %}" method="POST">
    {% csrf_token %}
    <table>
        <thead>
            <tr>
                <th>序号</th>
                <th>条形码</th>
                <th>商品名</th>
                <th>参考图</th>
                <th>品牌</th>
                <th>数量</th>
                <th>进货价</th>
                <th>零售价</th>
                <th>品类</th>
                <th>规格</th>
                <th>货架号</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <tr id="tpl" style="display: none">
                <th>0</th>
                <th>{{ form.barcode }}</th>
                <th>{{ form.goods_name }}</th>
                <th><img src="{{ form.pic.value }}" width="60" height="60" /></th>
                <th>{{ form.trade_mark }}</th>
                <th>{{ form.num }}{{ field.errors }}</th>
                <th>{{ form.input_price }}</th>
                <th>{{ form.sale_price }}</th>
                <th>{{ form.goods_class }}</th>
                <th>{{ form.spec }}</th>
                <th>{{ form.warehouse }}</th>
                <th>detail</th>
            </tr>
        </tbody>
    </table>
    <button name="submit">提交</button>
    <p>总计<span id="count">0</span>条</p>
</form>
{% endblock %}